spring:
  application:
    name: user
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: Zjkhhxl@1997
    # 可以使用不同的数据库，为了方便使用同一个数据库
    url: jdbc:mysql://139.196.140.168:3306/SpringCloud_Sell?characterEncoding=utf-8&useSSL=false
  rabbitmq:
    host: 139.196.140.168
    port: 5672
    username: guest
    password: guest
  redis:
    host: 139.196.140.168
    port: 6379
    password: hxl2580
  jpa:
    show-sql: true
env:
  dev
man:
  bat
